version: 2.1

workflows:
  run_tests:
    jobs:
      - test:
          filters:
            tags:
              only: /v?[0-9]+(\.[0-9]+)*/
          matrix:
            parameters:
              python_version: ["3.5","3.8"]
      - pypi:
          requires:
            - test
          filters:
            tags:
              only: /v?[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

jobs:
  test:
    parameters:
      python_version:
        type: string
    docker:
      - image: python:<< parameters.python_version >>
    working_directory: ~/flow-control-xblock
    steps:
      - checkout
      - run :
          name: Install requirements
          command: |
            pip install -r requirements/tox.txt
            apt install git
      - run:
          name: Run tox tests
          command: tox -e ${python_version//./}
    environment:
      - python_version: py<< parameters.python_version >>
  
  pypi:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run:
          name: Init .pypirc
          command: |
            echo $'[distutils]\nindex-servers = pypi\n[pypi]' > ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: Prepare venv for distribution
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install twine
      - run:
          name: Create package
          command: |
            python setup.py sdist bdist_wheel
      - run:
          name: Check package
          command: |
            source venv/bin/activate
            twine check dist/*
      - run:
          name: Upload to pypi
          command: |
            source venv/bin/activate
            twine upload dist/*
