version: 2.1

workflows:
  run_tests:
    jobs:
      - test:
          matrix:
            parameters:
              python_version: ["2.7"]

jobs:
  test:
    parameters:
      python_version:
        type: string
        default: "2.7"
    docker:
      - image: python:<< parameters.python_version >>
    working_directory: ~/flow-control-xblock
    steps:
      - checkout
      - run :
          name: Install requirements
          command: |
            pip install tox
            apt install git
      - run:
          name: Run tox tests
          command: tox -e ${python_version//./}
    environment:
      - python_version: py<< parameters.python_version >>
